# -*- coding: utf-8 -*-
"""Square.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/177iLejlCu2-a11TyfePKPQRsYZILWPSz
"""

import numpy as np

list1=[2,4,6,8,10]
for i in list1:
    print(i**2)

for i in list1:
    print(i**3)

def square(list1):
    return[i*2 for i in list1]

square(list1)

def cube(list1):
    return[i**3 for i in list1]

cube(list1)

